# Generated by Django 4.2.1 on 2023-05-31 14:28

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0003_alter_serviceprovider_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
        ),
    ]
