version: '3'
services:
  db:
    image: postgis/postgis
    environment:
      - POSTGRES_DB=roadlize
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db